import { ROUTES } from '@/lib/navigation/routes';
export const MAIN_CONTACT_CARDS = [
  {
    id: 'locate',
    href: ROUTES.caseStudyHouse,
    title: 'the case study house',
    tagline: 'locate & communicate ◦ parañaque city',
    subtext: 'our studio headquarters, address, interactive map, and contact coordinates.',
    description: 'Our studio headquarters, address, interactive map, and contact coordinates.',
    tags: ['Discovery Session', 'Locate & Communicate'],
    image: '/images/contact_headquarters_img_1785470005846.jpg',
  },
  {
    id: 'careers',
    href: ROUTES.growWithUs,
    title: 'grow with us',
    tagline: 'careers ◦ apprenticeship & regular programs',
    subtext: 'join our collaborative ecosystem. opportunities for emerging architects and design leaders.',
    description: 'Join our collaborative ecosystem. Opportunities for emerging architects and design leaders.',
    tags: ['Apprenticeship Programs', 'Regular Programs'],
    image: '/images/contact_careers_img_1785470018782.jpg',
  },
  {
    id: 'partners',
    href: ROUTES.partnerWithUs,
    title: 'partner with us',
    tagline: 'collaborations ◦ suppliers, consultants & builders',
    subtext: 'collaborate with ATBP as a material supplier, engineering consultant, or trade builder.',
    description: 'Collaborate with ATBP as a material supplier, engineering consultant, or trade builder.',
    tags: ['Suppliers', 'Consultants', 'Builders'],
    image: '/images/contact_partners_img_1785470031164.jpg',
  },
];

export const CASE_STUDY_HOUSE_CARDS = [
  {
    id: 'discovery',
    href: ROUTES.discoverySession,
    title: 'schedule a discovery session',
    tagline: 'intake, spatial goals & consultation',
    subtext: 'for project intake, site feasibility & spatial planning consultations',
    description: 'Start a dialogue with ATBP Collaborative for project planning, site feasibility, and design inquiries.',
    tags: ['Project Intake', 'Design Brief', 'Spatial Requirements'],
    image: '/images/studio_services_img_1785469964556.jpg',
  },
  {
    id: 'request-proposal',
    href: ROUTES.requestForProposal,
    title: 'request a proposal',
    tagline: 'project scoping & preliminary quotations',
    subtext: 'for official cost estimates and formal project proposals',
    description: 'Submit your project details for a formal proposal, preliminary quotation, and architectural scoping.',
    tags: ['Quotations', 'Project Scoping', 'Proposals'],
    image: '/images/production_drawings_1783495233053.jpg',
  },
  {
    id: 'locate-map',
    href: ROUTES.contactInfo,
    title: 'studio hours & location',
    tagline: 'headquarters, address & contact channels',
    subtext: 'for physical visits, interactive map & contact coordinates',
    description: 'Interactive office map, physical address in Parañaque City, landline, mobile, Viber & social channels.',
    tags: ['Parañaque City', 'Interactive Map', 'Viber & Email'],
    image: '/images/contact_headquarters_img_1785470005846.jpg',
  },
];

export const GROW_WITH_US_CARDS = [
  {
    id: 'apprenticeship',
    href: ROUTES.apprenticeshipPrograms,
    title: 'apprenticeship programs',
    tagline: 'for on-the-job training requirements',
    subtext: 'for on-the-job training requirements',
    description: 'Comprehensive mentorship path for architecture graduates preparing for professional licensure and site management.',
    tags: ['Junior Architect', 'Licensure Support', 'Site Experience'],
    image: '/images/studio_people_img_1785469993286.jpg',
  },
  {
    id: 'studio-regulars',
    href: ROUTES.regularPrograms,
    title: 'regular programs',
    tagline: 'for professionals',
    subtext: 'for professionals',
    description: 'Leadership roles for registered architects, spatial strategists, and project directors driving studio commissions.',
    tags: ['Registered Architect', 'Project Director', 'Design Lead'],
    image: '/images/production_drawings_1783495233053.jpg',
  },
];

export const PARTNER_WITH_US_CARDS = [
  {
    id: 'suppliers',
    href: ROUTES.supplier,
    title: 'suppliers',
    tagline: 'for material suppliers & trade product specs',
    subtext: 'for material suppliers & trade product specs',
    description: 'Register material samples, architectural fixtures, sustainable building assemblies, and trade products with ATBP.',
    tags: ['Material Specification', 'Bespoke Finishes', 'Hardware'],
    image: '/images/contact_partners_img_1785470031164.jpg',
  },
  {
    id: 'consultants',
    href: ROUTES.consultant,
    title: 'consultants',
    tagline: 'for engineering & specialist consultants',
    subtext: 'for engineering & specialist consultants',
    description: 'Collaborate as a structural engineer, MEPFS specialist, environmental analyst, or technical peer reviewer.',
    tags: ['Structural', 'MEPFS', 'Environmental Review'],
    image: '/images/studio_process_img_1785469980353.jpg',
  },
  {
    id: 'builders',
    href: ROUTES.builder,
    title: 'builders',
    tagline: 'for general contractors & master builders',
    subtext: 'for general contractors & master builders',
    description: 'Partner as a general contractor, specialized mason, steel fabricator, or custom joinery artisan on studio builds.',
    tags: ['General Contractors', 'Masonry & Steel', 'Joinery Artisans'],
    image: '/images/retail_boutique_1783495217375.jpg',
  },
];
