import { Project, Service } from './types';

// Let's use the exact image paths generated by our tool
export const PROJECTS_DATA: Project[] = [
  {
    id: 'case-study-house',
    title: 'The Case Study House No. 1',
    category: 'Urban Living',
    mainCategory: 'Shelter',
    subcategory: 'Urban Living',
    location: 'Countryside Village, Parañaque',
    year: '2025',
    clientType: 'High-Income',
    description: 'A monolithic concrete villa integrated with warm timber wood screens, maximizing passive cooling and elegant negative space.',
    fullWriteup: 'This residence serves as the practice\'s core prototype for tropical minimalist living. Structured with raw off-form board-marked concrete, the building responds directly to the local Philippine climate. Operable timber slats envelop the front facade, acting as a dynamic visual buffer that filters harsh afternoon sunlight while encouraging cross-ventilation. Inside, open-plan spaces merge seamlessly with linear green courtyards, blurring the lines between structural sanctuary and natural landscape.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/retail_boutique_1783495217375.jpg',
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    video: 'https://www.youtube.com/watch?v=Z9GcCLUJG8Y',
    status: 'completed',
    specs: {
      area: '420 sqm',
      scope: 'comprehensive design',
      duration: '14 Months',
      materials: ['Off-Form Concrete', 'Recycled Teakwood', 'Travertine Stone', 'Low-E Insulated Glass']
    }
  },
  {
    id: 'sovereign-suites',
    title: 'Sovereign Condo Fit-Out',
    category: 'Urban Living',
    mainCategory: 'Shelter',
    subcategory: 'Urban Living',
    location: 'BGC, Taguig City',
    year: '2025',
    clientType: 'Mid-High-Income',
    description: 'An executive condominium overhaul focusing on built-in modularity, custom Rose Ebony paneling, and indirect architectural lighting.',
    fullWriteup: 'Confronted with the structural constraints of standard high-rise units, our design maximizes spatial volume through bespoke vertical cabinetry and recessed details. We created a continuous Rose Ebony wood skin that conceals utility access and storage, organizing the flow of the kitchen, dining, and living chambers. Travertine flooring paired with custom linen drapes amplifies daylight, turning a compact layout into an editorial-grade residential haven.',
    images: [
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/retail_boutique_1783495217375.jpg',
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    status: 'completed',
    specs: {
      area: '125 sqm',
      scope: 'general construction',
      duration: '4 Months',
      materials: ['Rose Ebony Veneer', 'Travertine Slabs', 'Brushed Copper', 'Warm Cove LED']
    }
  },
  {
    id: 'sierra-tiny-living',
    title: 'Sierra Micro Cabin Prototype',
    category: 'Tiny Living',
    mainCategory: 'Shelter',
    subcategory: 'Tiny Living',
    location: 'Sierra Madre foothills, Tanay',
    year: '2025',
    clientType: 'Mid-Income',
    description: 'An off-grid 32 sqm micro-dwelling engineered for extreme spatial efficiency and panoramic nature views.',
    fullWriteup: 'Designed as a modular off-grid prototype, the Sierra Micro Cabin demonstrates how minimal footprints can deliver expansive architectural experiences. Folding facade screens, transformer furniture, and rain-harvesting overhangs harmonize high-density comfort with untouched mountain ecology.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg'
    ],
    status: 'schematics',
    specs: {
      area: '32 sqm',
      scope: 'comprehensive design',
      duration: '3 Months',
      materials: ['Modular Steel Framing', 'Charred Yakisugi Wood', 'Double Glazed Glass']
    }
  },
  {
    id: 'horizon-penthouse',
    title: 'Horizon Sky Penthouse',
    category: 'Penthouses',
    mainCategory: 'Shelter',
    subcategory: 'Penthouses',
    location: 'Rockwell Center, Makati',
    year: '2026',
    clientType: 'High-Income',
    description: 'A dual-level penthouse sanctuary with floating spiral staircase, custom brass screens, and panoramic city views.',
    fullWriteup: 'Perched on the top floors of Rockwell, this penthouse combines double-height volumes with dark smoked oak, fluted marble slabs, and custom ambient cove systems.',
    images: [
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg'
    ],
    status: 'ongoing',
    specs: {
      area: '510 sqm',
      scope: 'comprehensive design',
      duration: '10 Months',
      materials: ['Calacatta Marble', 'Smoked Oak', 'Brushed Brass']
    }
  },
  {
    id: 'amparo-bnb',
    title: 'Amparo Boutique BNB Retreat',
    category: 'Retail & Lifestyle',
    mainCategory: 'Livelihood',
    subcategory: 'Retail & Lifestyle',
    location: 'Tagaytay Ridge, Cavite',
    year: '2024',
    clientType: 'High-Income',
    description: 'A 6-suite hospitality retreat integrating lush gardens, central plunge pool, and natural ventilation courtyards.',
    fullWriteup: 'Amparo BNB balances private guest suites with shared communal pavilions, utilizing exposed bamboo ceiling joists, clay tile roofing, and handcrafted stone masonry.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    status: 'completed',
    specs: {
      area: '680 sqm',
      scope: 'comprehensive design',
      duration: '12 Months',
      materials: ['Terracotta Tiles', 'Bamboo Joists', 'Volcanic Ash Plaster']
    }
  },
  {
    id: 'soluna-villas',
    title: 'Soluna Twin Villas (Build & Sell)',
    category: 'Build & Sell Homes',
    mainCategory: 'Livelihood',
    subcategory: 'Build & Sell Homes',
    location: 'Loyola Grand Villas, Quezon City',
    year: '2025',
    clientType: 'Mid-High-Income',
    description: 'Optimized twin residential development engineered for rapid construction deployment and maximum market value.',
    fullWriteup: 'A high-yield build-and-sell design strategy offering dual luxury units with synchronized structural grids, shared driveway access, and distinct architectural facade accents.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/production_drawings_1783495233053.jpg'
    ],
    status: 'completed',
    specs: {
      area: '600 sqm',
      scope: 'general construction',
      duration: '8 Months',
      materials: ['Precast Concrete Panels', 'Powder Coated Aluminum']
    }
  },
  {
    id: 'the-velvet-rack',
    title: 'The Velvet Rack Boutique',
    category: 'Retail & Lifestyle',
    mainCategory: 'Livelihood',
    subcategory: 'Retail & Lifestyle',
    location: 'Rockwell, Makati',
    year: '2024',
    clientType: 'High-Income',
    description: 'An upscale clothing boutique styled with warm sand-textured plaster walls, travertine arches, and custom structural steel hangers.',
    fullWriteup: 'The Velvet Rack boutique explores the intersection of high fashion and structural weight. By moving away from conventional white retail boxes, we sculpted the store from textured warm plaster and natural travertine stone. Massive arched portals divide different clothing collections, while bespoke structural raw-steel clothes hangers trace elegant lines against the rough walls, creating a powerful, tactile dialogue.',
    images: [
      '/src/assets/images/retail_boutique_1783495217375.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    status: 'completed',
    specs: {
      area: '180 sqm',
      scope: 'comprehensive design',
      duration: '3.5 Months',
      materials: ['Sanded Stucco', 'Raw Structural Steel', 'Honed Travertine', 'Custom Architectural Spotlights']
    }
  },
  {
    id: 'origin-espresso',
    title: 'Origin Coffee Kiosk',
    category: 'Food & Beverage',
    mainCategory: 'Livelihood',
    subcategory: 'Food & Beverage',
    location: 'Alabang Town Center, Muntinlupa',
    year: '2024',
    clientType: 'Mid-Income',
    description: 'A modular, lightweight specialty coffee station featuring raw concrete countertops and polished structural steel accents.',
    fullWriteup: 'Origin Espresso is a modern response to transit coffee retail. Occupying a tight 15-sqm footprint, we engineered a high-volume workstation encased in lightweight cast-concrete and reflective stainless steel. The design leverages smart-wiring and integrated plumbing channels to maintain a perfectly clean counter, elevating the customer-barista interaction into a highly focused sensory performance.',
    images: [
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/retail_boutique_1783495217375.jpg',
      '/src/assets/images/production_drawings_1783495233053.jpg'
    ],
    status: 'completed',
    specs: {
      area: '15 sqm',
      scope: 'piecework',
      duration: '45 Days',
      materials: ['Lightweight Concrete Slabs', 'Mirror Stainless Steel', 'Walnut Accents']
    }
  },
  {
    id: 'production-outsourcing',
    title: 'Production Drawing Outsourcing',
    category: 'Workspaces',
    mainCategory: 'Livelihood',
    subcategory: 'Workspaces',
    location: 'Global / B2B Services',
    year: 'Ongoing',
    clientType: 'High-Income',
    description: 'Comprehensive construction document sets, detailed shop drawings, and BIM execution models for international and local architectural firms.',
    fullWriteup: 'We collaborate with design-focused practices worldwide to translate their conceptual sketches into fully executable, permit-ready construction drawing packages. By utilizing advanced CAD standards, detailed material specifications, and BIM coordination models, we serve as a seamless technical extension, enabling overseas firms to maintain impeccable execution standards without administrative overhead.',
    images: [
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg',
      '/src/assets/images/retail_boutique_1783495217375.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    status: 'ongoing',
    specs: {
      scope: 'retainer services',
      duration: 'Contractual / Project-Based',
      materials: ['Autodesk Revit', 'AutoCAD Precise Sets', 'BIM Coordination']
    }
  },
  {
    id: 'civic-fire-station',
    title: 'District 04 Rescue & Fire Station',
    category: 'Shared Places',
    mainCategory: 'Community',
    subcategory: 'Shared Places',
    location: 'Valenzuela City',
    year: '2025',
    clientType: 'Mid-Income',
    description: 'A high-performance municipal emergency response facility engineered for rapid vehicular dispatch and resilient civic architecture.',
    fullWriteup: 'Designed to optimize turn-around speed for emergency vehicles while providing high-end living quarters, training bays, and community dispatch hubs built with cast-in-place concrete.',
    images: [
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/hero_modern_villa_1783495183350.jpg'
    ],
    status: 'schematics',
    specs: {
      area: '1,200 sqm',
      scope: 'comprehensive design',
      duration: '18 Months',
      materials: ['Reinforced Structural Concrete', 'Heavy Industrial Steel Doors']
    }
  },
  {
    id: 'santa-clara-convent',
    title: 'Santa Clara Sanctuary & Convent',
    category: 'Sacred Structures',
    mainCategory: 'Community',
    subcategory: 'Sacred Structures',
    location: 'Antipolo, Rizal',
    year: '2024',
    clientType: 'Mid-High-Income',
    description: 'A contemplative religious complex featuring enclosed cloister gardens, acoustically tuned chapel, and minimalist living quarters.',
    fullWriteup: 'Designed around quiet introspection and acoustic clarity, the convent incorporates raw masonry arches, diffused clerestory windows, and tranquil central water courtyards.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/condo_fitout_interior_1783495200802.jpg'
    ],
    status: 'completed',
    specs: {
      area: '1,850 sqm',
      scope: 'comprehensive design',
      duration: '16 Months',
      materials: ['Custom Brick Masonry', 'Natural Timber Screens', 'Acoustic Plaster']
    }
  },
  {
    id: 'balintawak-plaza',
    title: 'Balintawak Heritage Open Plaza',
    category: 'Shared Places',
    mainCategory: 'Community',
    subcategory: 'Shared Places',
    location: 'Quezon City',
    year: '2025',
    clientType: 'Mid-Income',
    description: 'A urban civic plaza masterplan integrating permeable pavers, native shade trees, and sunken amphitheater seating.',
    fullWriteup: 'Transforming an underutilized urban plot into a resilient public park, complete with storm runoff bio-swales and modular outdoor gathering stages.',
    images: [
      '/src/assets/images/hero_modern_villa_1783495183350.jpg',
      '/src/assets/images/retail_boutique_1783495217375.jpg'
    ],
    status: 'ongoing',
    specs: {
      area: '3,500 sqm',
      scope: 'comprehensive design',
      duration: '12 Months',
      materials: ['Permeable Concrete Pavers', 'Weathering Corten Steel']
    }
  },
  {
    id: 'community-commons',
    title: 'Barangay Community Commons',
    category: 'Shared Spaces',
    mainCategory: 'Community',
    subcategory: 'Shared Spaces',
    location: 'San Juan City',
    year: '2025',
    clientType: 'Mid-Income',
    description: 'A multi-purpose civic pavilion hosting neighborhood assemblies, youth learning centers, and disaster relief operations.',
    fullWriteup: 'A highly flexible community building featuring operable louver panels, double-height assembly halls, and solar canopy roofs.',
    images: [
      '/src/assets/images/production_drawings_1783495233053.jpg',
      '/src/assets/images/kiosk_coffee_bar_1783495252161.jpg'
    ],
    status: 'completed',
    specs: {
      area: '750 sqm',
      scope: 'general construction',
      duration: '7 Months',
      materials: ['Exposed Structural Steel Framing', 'Polished Concrete Floors']
    }
  }
];

export const SERVICES_DATA: Service[] = [
  {
    title: 'comprehensive design',
    iconName: 'Layers',
    desc: 'Full-envelope design solutions encompassing conceptual planning, structural, MEPFS documents, BIM modeling, and permitting support.'
  },
  {
    title: 'piecework',
    iconName: 'LayoutGrid',
    desc: 'Targeted architectural detailing, modular kitchen/bath designs, single spaces, or individual drawing sets billed per deliverable.'
  },
  {
    title: 'general construction',
    iconName: 'Briefcase',
    desc: 'Complete turn-key physical construction management. Ground-up masonry, civil works, architectural finishing, and site coordination.'
  },
  {
    title: 'retainer services',
    iconName: 'RefreshCw',
    desc: 'Ongoing design, BIM outsourcing, and drafting support acting as a dedicated technical back-office for global architectural firms.'
  }
];

